### ISSUE TITLE
Does this support telegram like animated icon?

### ISSUE THREAD

**Issue by nandgator** [Frezyx/animated_icon_button#10]
![video-2021-04-30-11-32-08](https://user-images.githubusercontent.com/38415384/116655246-65a76080-a9a8-11eb-965c-8acf45dca378.gif)

Pointers on how to achieve this (icon swapping - with / without theme switching animation) on flutter will be really helpful..

**Comment by Frezyx** [comment]
Hello @joe733 !
Now this package does not support this functionality.

**Comment by Frezyx** [comment]
But you can use this package with [animated_theme_switcher](https://pub.dev/packages/animated_theme_switcher)
to achieve a similar result.

**Comment by nandgator** [comment]
Hi, thanks, I already had came across [animated_theme_switcher](https://pub.dev/packages/animated_theme_switcher), I was wondering if those ☀️ and 🌙 icon pairs where available in this package. If not can I make it possible through custom method? 

PS: starred 🌟 this repo!

**Comment by Frezyx** [comment]
With this package you can use any icons from any package
Like font_awesome / material / cupertino

**Comment by nandgator** [comment]
So.. that telegram like animation is quite possible with [animated_icon_button](https://github.com/Frezyx/animated_icon_button) + [animated_theme_switcher](https://pub.dev/packages/animated_theme_switcher)! Thanks!

**Comment by Frezyx** [comment]
Thanks you for supporting the repository
