### ISSUE TITLE
Migrate to NNBD

### ISSUE THREAD

**Issue by SirusCodes** [Frezyx/animated_icon_button#4]
Migrating this package to null-safety would be really great.
https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

**Comment by Frezyx** [comment]
Hello @SirusCodes ! 
Thank you for this issue 👍🏻 
I will check pr from @prasadsunny1 soon.

**Comment by Frezyx** [comment]
Pr https://github.com/Frezyx/animated_icon_button/pull/5 was merged.
This changes will be available in next package update on pub.dev.

**Comment by SirusCodes** [comment]
Congratulations @prasadsunny1 🎉
