### ISSUE TITLE
Feature Request - binding to boolean

### ISSUE THREAD

**Issue by jlnrrg** [Frezyx/animated_icon_button#7]
I know this might lead to breaking changes, but I'd like to voice my request nevertheless.
It would be great if the widget would not focus on start and end icon, but determines the icon based on a boolean, as most switches do.
The benefit here would be that I could bind it to another value, thus making the start value always right accordingly.

**Comment by Frezyx** [comment]
Hello @jlnrrg 👋🏻 
You can use **animationController** for this if I understand you right.

**Comment by jlnrrg** [comment]
@Frezyx thanks for reminding me of the animationController, with which it might work.

my concrete example is, that I have a boolean stored in a db and based on it want to set the animatedButton. 
Here I'd normally assume something like an initialValue, as the solution with an animationcontroller would be quite hacky

**Comment by Frezyx** [comment]
Thats cool 👍🏻 

Thanks for using this package!
I would be happy if you put an star for this repository 😃

**Comment by jlnrrg** [comment]
@Frezyx even though there might be a workaround to this, I think it should be properly addressed nevertheless, because it drastically reduces the entry barrier for new flutter programmers.

 I will submit a pull request for the changes I have in mind, but would first like to talk it through with you, if you are open for changes and how breaking they are allowed to be.
Feel free to message me via telegram, link is in my profile

**Comment by Frezyx** [comment]
The package is open to any changes.  You are a developer with your own vision. I will be glad to see this functionality.
