### ISSUE TITLE
Icons not following Theme

### ISSUE THREAD

**Issue by SirusCodes** [Frezyx/animated_icon_button#9]
In 1.0.0 Icons are not following color from theme and shows ThemeData.disabledColor

```dart
AnimatedIconButton(
    size: 25,
    animationController: _iconController,
    icons: const [
        AnimatedIconItem(icon: Icon(Icons.share)),
        AnimatedIconItem(icon: Icon(Icons.close_rounded)),
    ],
),
```

**Comment by Frezyx** [comment]
Hello @SirusCodes 👋🏻 
Big thanks for reporting this !
I will check this bug soon.

**Comment by SirusCodes** [comment]
Thanks a lot ❤️

**Comment by jlnrrg** [comment]
@SirusCodes which would be the ThemeData you'd expect it to follow?
I personally use the AnimatedIconButton as a FloatingActionButton replacement, but I doubt that this is true for everyone. So it would be great if you could specify which `Theme.of(context). <-` you'd expect.

**Comment by SirusCodes** [comment]
> @SirusCodes which would be the ThemeData you'd expect it to follow?
> I personally use the AnimatedIconButton as a FloatingActionButton replacement, but I doubt that this is true for everyone. So it would be great if you could specify which `Theme.of(context). <-` you'd expect.

I don't have any problem with using `Theme.of(context)` but new update has some changes which changed the expected behaviour.

**Comment by jlnrrg** [comment]
As I basicly made a lot of major improvements without the state of the art in mind, my question is what the expected behaviour is. 
Also there are multiple entries under Theme. of(contex)
Themes for Elevatedbutton or Outlinedbutton, to name a few.

**Comment by SirusCodes** [comment]
I expect it to be of default Icon color as in [flutter docs](https://api.flutter.dev/flutter/widgets/Icon/color.html)

**Comment by Frezyx** [comment]
Hello @SirusCodes ! ✋🏻 
I was able to find time for this question only now.
Sorry for your waiting

Icons take this color due to the fact that you do not pass **onPressed** callback.
You can pass this field and icon will become the same color as in the theme.
This practice is standard for IconButton widgets.

**Comment by SirusCodes** [comment]
Ohh @Frezyx I will verify this, thanks for your time.
